#!/bin/bash
# =============================================================================
# TORRENT-CONTAINER - Container setup, config, and lifecycle management
# =============================================================================
# Creates and manages Gluetun + qBittorrent Podman containers with
# configurable VPN provider, protocol, and Podman secrets for credentials.
#
# Commands:
#   install  - Interactive setup (provider, credentials, countries)
#   info     - Show current configuration and container status
#   edit     - Modify config interactively, recreate containers
#   update   - Pull latest images and recreate if updated
#   delete   - Remove containers, secrets, and config
#
# Module: torrent
# Requires: core, config, ui
# Version: 0.1.0
#
# Usage:
#   torrent-container                    # Interactive menu
#   torrent-container install            # Full interactive setup
#   torrent-container info               # Show current config
#   torrent-container edit               # Modify and recreate
#   torrent-container update             # Pull + recreate images
#   torrent-container delete             # Remove everything
# =============================================================================

set -euo pipefail
trap 'echo "ERROR: torrent-container failed at line $LINENO" >&2; exit 1' ERR

# ===================
# Load shared library
# ===================
readonly LIB_DIR="/usr/local/lib/system-scripts"
source "$LIB_DIR/core.sh"
source "$LIB_DIR/config.sh"
source "$LIB_DIR/ui.sh"

# =============================================================================
# CONSTANTS
# =============================================================================
readonly IMAGE_GLUETUN="docker.io/qmcgaw/gluetun"
readonly IMAGE_QBITTORRENT="lscr.io/linuxserver/qbittorrent:latest"
readonly CONTAINER_CONF="${TORRENT_CONTAINER_CONF:-$HOME/.config/torrent/container.conf}"
readonly CONTAINER_DATA_DIR="${TORRENT_DATA_DIR:-$HOME/.config/podman/containers}"

ACTION="${1:-}"

# ===================
# Provider data
# ===================

# Credential patterns:
#   openvpn_user_pass     - username + password (most providers)
#   openvpn_user_only     - account ID only (mullvad)
#   wireguard_key         - private key only
#   wireguard_key_addr    - private key + address (mullvad, surfshark)
declare -A PROVIDER_CREDS=(
    ["protonvpn:openvpn"]="openvpn_user_pass"
    ["protonvpn:wireguard"]="wireguard_key"
    ["mullvad:openvpn"]="openvpn_user_only"
    ["mullvad:wireguard"]="wireguard_key_addr"
    ["nordvpn:openvpn"]="openvpn_user_pass"
    ["nordvpn:wireguard"]="wireguard_key"
    ["surfshark:openvpn"]="openvpn_user_pass"
    ["surfshark:wireguard"]="wireguard_key_addr"
)

declare -A PROVIDER_HELP=(
    ["protonvpn:openvpn"]="https://account.protonvpn.com/account#openvpn"
    ["protonvpn:wireguard"]="https://account.protonvpn.com/downloads#wireguard-configuration"
    ["mullvad:openvpn"]="https://mullvad.net/en/account"
    ["mullvad:wireguard"]="https://mullvad.net/en/account/wireguard-config"
    ["nordvpn:openvpn"]="https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/"
    ["nordvpn:wireguard"]="https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/"
    ["surfshark:openvpn"]="https://my.surfshark.com/vpn/manual-setup"
    ["surfshark:wireguard"]="https://my.surfshark.com/vpn/manual-setup/main/wireguard"
)

# Providers that support FREE_ONLY toggle
readonly FREE_ONLY_PROVIDERS="protonvpn"

# All supported provider names (for ui_choose)
readonly PROVIDERS="protonvpn mullvad nordvpn surfshark"

# =============================================================================
# CONFIG FUNCTIONS
# =============================================================================

load_container_config() {
    if [[ ! -f "$CONTAINER_CONF" ]]; then
        return 1
    fi
    # shellcheck source=/dev/null
    source "$CONTAINER_CONF"
}

save_container_config() {
    local provider="$1" vpn_type="$2" countries="$3" free_only="$4"
    local tz="$5" puid="$6" pgid="$7"
    local wg_addresses="${8:-}" api_key="${9:-}"

    mkdir -p "$(dirname "$CONTAINER_CONF")"

    {
        printf '# Torrent container configuration\n'
        printf '# Generated by torrent-container on %s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
        printf 'PROVIDER=%s\n' "$provider"
        printf 'VPN_TYPE=%s\n' "$vpn_type"
        printf 'COUNTRIES="%s"\n' "$countries"
        printf 'FREE_ONLY=%s\n' "$free_only"
        printf 'TZ=%s\n' "$tz"
        printf 'PUID=%s\n' "$puid"
        printf 'PGID=%s\n' "$pgid"
        if [[ -n "$wg_addresses" ]]; then
            printf 'WIREGUARD_ADDRESSES=%s\n' "$wg_addresses"
        fi
        printf 'GLUETUN_API_KEY=%s\n' "$api_key"
    } > "$CONTAINER_CONF"

    chmod 600 "$CONTAINER_CONF"
}

# =============================================================================
# PODMAN SECRET FUNCTIONS
# =============================================================================

secret_set() {
    local name="$1"
    local value="$2"
    podman secret rm "$name" 2>/dev/null || true
    printf '%s' "$value" | podman secret create "$name" -
}

secret_exists() {
    podman secret inspect "$1" &>/dev/null
}

secret_remove() {
    podman secret rm "$1" 2>/dev/null || true
}

secrets_remove_all() {
    local names=(
        torrent-openvpn-user torrent-openvpn-password
        torrent-wireguard-key torrent-wireguard-psk
    )
    for name in "${names[@]}"; do
        secret_remove "$name"
    done
}

# Return space-separated list of secret names needed for a provider+type
secrets_needed() {
    local provider="$1"
    local vpn_type="$2"
    local key="${provider}:${vpn_type}"
    local cred="${PROVIDER_CREDS[$key]:-}"

    case "$cred" in
        openvpn_user_pass)  echo "torrent-openvpn-user torrent-openvpn-password" ;;
        openvpn_user_only)  echo "torrent-openvpn-user" ;;
        wireguard_key)      echo "torrent-wireguard-key" ;;
        wireguard_key_addr) echo "torrent-wireguard-key" ;;
        *) error "Unknown credential pattern for $key" "exit" ;;
    esac
}

# Build --secret flags for podman run (one element per line for array reading)
build_secret_flags() {
    local provider="$1"
    local vpn_type="$2"
    local key="${provider}:${vpn_type}"
    local cred="${PROVIDER_CREDS[$key]:-}"

    case "$cred" in
        openvpn_user_pass)
            echo "--secret"
            echo "torrent-openvpn-user,type=env,target=OPENVPN_USER"
            echo "--secret"
            echo "torrent-openvpn-password,type=env,target=OPENVPN_PASSWORD"
            ;;
        openvpn_user_only)
            echo "--secret"
            echo "torrent-openvpn-user,type=env,target=OPENVPN_USER"
            ;;
        wireguard_key)
            echo "--secret"
            echo "torrent-wireguard-key,type=env,target=WIREGUARD_PRIVATE_KEY"
            ;;
        wireguard_key_addr)
            echo "--secret"
            echo "torrent-wireguard-key,type=env,target=WIREGUARD_PRIVATE_KEY"
            ;;
    esac
}

# =============================================================================
# CONTAINER FUNCTIONS
# =============================================================================

container_exists() {
    podman ps -a --format "{{.Names}}" 2>/dev/null | grep -q "^${1}$"
}

container_running() {
    podman ps --format "{{.Names}}" 2>/dev/null | grep -q "^${1}$"
}

remove_containers() {
    for ct in qbittorrent gluetun; do
        if container_exists "$ct"; then
            podman stop -t 10 "$ct" 2>/dev/null || true
            podman rm "$ct" 2>/dev/null || true
        fi
    done
}

# =============================================================================
# HEALTH CHECK FUNCTIONS
# =============================================================================

# Poll gluetun's control server for VPN readiness
# Uses /v1/publicip/ip which works for both openvpn and wireguard
poll_gluetun_health() {
    local max_wait="${1:-120}"
    local interval=3
    local elapsed=0

    while [[ $elapsed -lt $max_wait ]]; do
        local response
        response=$(curl -s --max-time 3 \
            -H "X-API-Key: ${GLUETUN_API_KEY:-}" \
            "http://localhost:18001/v1/publicip/ip" 2>/dev/null) || true
        if echo "$response" | grep -q '"public_ip"' 2>/dev/null; then
            echo ""
            return 0
        fi
        echo -n "."
        sleep "$interval"
        ((elapsed += interval))
    done
    echo ""
    return 1
}

# Poll for container running state
poll_container_running() {
    local name="$1"
    local max_wait="${2:-30}"
    local elapsed=0

    while [[ $elapsed -lt $max_wait ]]; do
        if container_running "$name"; then
            return 0
        fi
        sleep 1
        ((elapsed++))
    done
    return 1
}

# =============================================================================
# CONTAINER CREATION — Single source of truth
# =============================================================================

create_containers() {
    # Load paths (DOWNLOAD_DIR from paths.conf, derive TORRENT_DIR)
    load_config
    TORRENT_DIR="$DOWNLOAD_DIR/torrents"

    # Load container config
    if ! load_container_config; then
        error "Container configuration not found: $CONTAINER_CONF" "exit"
    fi

    # --- Build gluetun env vars ---
    # shellcheck disable=SC2153  # Variables assigned by load_container_config
    local gluetun_env=(
        -e "VPN_SERVICE_PROVIDER=$PROVIDER"
        -e "VPN_TYPE=$VPN_TYPE"
        -e "SERVER_COUNTRIES=$COUNTRIES"
        -e "FREE_ONLY=$FREE_ONLY"
        -e "DNS_SERVER=off"
        -e "DNS_ADDRESS=1.1.1.1"
        -e "DNS_FALLBACK_ADDRESS=8.8.8.8"
        -e "HTTPPROXY=off"
        -e "SHADOWSOCKS=off"
        -e "HTTP_CONTROL_SERVER_ADDRESS=:18001"
        -e "HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={\"auth\":\"apikey\",\"apikey\":\"$GLUETUN_API_KEY\"}"
        -e "FIREWALL=on"
        -e "FIREWALL_VPN_INPUT_PORTS=6881"
    )

    # WireGuard addresses (required by some providers)
    if [[ "$VPN_TYPE" == "wireguard" && -n "${WIREGUARD_ADDRESSES:-}" ]]; then
        gluetun_env+=(-e "WIREGUARD_ADDRESSES=$WIREGUARD_ADDRESSES")
    fi

    # --- Build secret flags ---
    local secret_flags=()
    while IFS= read -r line; do
        [[ -n "$line" ]] && secret_flags+=("$line")
    done < <(build_secret_flags "$PROVIDER" "$VPN_TYPE")

    # --- Remove leftover auth config file (replaced by env var) ---
    rm -f "$CONTAINER_DATA_DIR/gluetun/auth/config.toml"

    # --- Create gluetun ---
    info "Creating gluetun container..."
    podman run -d \
        --name gluetun \
        --privileged \
        --cap-add NET_ADMIN \
        --device /dev/net/tun:/dev/net/tun \
        "${gluetun_env[@]}" \
        "${secret_flags[@]}" \
        -p 18002:18002 \
        -p 18001:18001 \
        -p 6881:6881 \
        -p 6881:6881/udp \
        -v "$CONTAINER_DATA_DIR/gluetun:/gluetun:Z" \
        --restart unless-stopped \
        "$IMAGE_GLUETUN"

    # --- Wait for gluetun VPN connection ---
    info "Waiting for VPN connection..."
    if ! poll_gluetun_health 120; then
        error "Gluetun failed to connect within 120s"
        echo -e "  Check logs: ${C_CYAN}podman logs gluetun${C_NC}"
        return 1
    fi
    success "Gluetun VPN connected"

    # --- Create qbittorrent ---
    info "Creating qBittorrent container..."
    # shellcheck disable=SC2153  # Variables assigned by load_container_config
    podman run -d \
        --name qbittorrent \
        --network container:gluetun \
        -e "PUID=$PUID" \
        -e "PGID=$PGID" \
        -e "TZ=$TZ" \
        -e WEBUI_PORT=18002 \
        -v "$TORRENT_DIR:/downloads:Z" \
        -v "$CONTAINER_DATA_DIR/qbittorrent:/config:Z" \
        --restart unless-stopped \
        "$IMAGE_QBITTORRENT"

    # --- Wait for qbittorrent to start ---
    if ! poll_container_running "qbittorrent" 30; then
        error "qBittorrent failed to start within 30s"
        return 1
    fi
    success "qBittorrent container created"
}

# =============================================================================
# INTERACTIVE PROMPT FUNCTIONS
# =============================================================================

prompt_provider() {
    # shellcheck disable=SC2086
    ui_choose --header "Select VPN provider" $PROVIDERS
}

prompt_vpn_type() {
    local provider="$1"
    local types=()

    [[ -n "${PROVIDER_CREDS["$provider:openvpn"]:-}" ]] && types+=("openvpn")
    [[ -n "${PROVIDER_CREDS["$provider:wireguard"]:-}" ]] && types+=("wireguard")

    if [[ ${#types[@]} -eq 1 ]]; then
        echo "${types[0]}"
        return
    fi

    ui_choose --header "VPN protocol" "${types[@]}"
}

# Curated list of torrent-friendly countries (privacy laws, no data retention)
readonly TORRENT_COUNTRIES=(Netherlands Switzerland Sweden Romania Spain Canada)

prompt_countries() {
    local default="${1:-}"
    local selected=()

    if has_gum; then
        # Multi-select with gum (space to toggle, enter to confirm)
        mapfile -t selected < <(
            gum choose --no-limit \
                --header "Server countries (space to select, enter to confirm)" \
                "${TORRENT_COUNTRIES[@]}" "Other"
        )
    else
        # Fallback: numbered list, multiple numbers separated by spaces
        echo -e "  ${C_BOLD}Server countries${C_NC} (enter numbers separated by spaces):" >&2
        local i=1
        for country in "${TORRENT_COUNTRIES[@]}" "Other"; do
            echo -e "    ${C_BOLD}$i)${C_NC} $country" >&2
            ((i++))
        done
        local input
        read -r -p "  Selection: " input
        local total=$(( ${#TORRENT_COUNTRIES[@]} + 1 ))
        for num in $input; do
            if [[ "$num" =~ ^[0-9]+$ ]] && (( num >= 1 && num <= total )); then
                if (( num <= ${#TORRENT_COUNTRIES[@]} )); then
                    selected+=("${TORRENT_COUNTRIES[$((num-1))]}")
                else
                    selected+=("Other")
                fi
            fi
        done
    fi

    # Check if "Other" was selected
    local has_other=false
    local countries=()
    for item in "${selected[@]}"; do
        if [[ "$item" == "Other" ]]; then
            has_other=true
        else
            countries+=("$item")
        fi
    done

    if [[ "$has_other" == true ]]; then
        # Pre-fill with selected countries from list (or default)
        local prefill=""
        if [[ ${#countries[@]} -gt 0 ]]; then
            prefill=$(IFS=,; echo "${countries[*]}")
        else
            prefill="$default"
        fi
        local result
        result=$(ui_input "Server countries (comma-separated)" "$prefill")
        echo "${result:-Netherlands}"
    elif [[ ${#countries[@]} -gt 0 ]]; then
        IFS=,; echo "${countries[*]}"
    else
        echo "${default:-Netherlands}"
    fi
}

prompt_free_only() {
    local provider="$1"
    if [[ "$FREE_ONLY_PROVIDERS" == *"$provider"* ]]; then
        ui_choose --header "Use free servers only?" "off" "on"
    else
        echo "off"
    fi
}

# Common European timezones + UTC
readonly TIMEZONES="Europe/Amsterdam Europe/Paris Europe/London Europe/Berlin Europe/Brussels Europe/Zurich Europe/Rome Europe/Madrid UTC"

detect_timezone() {
    local default="${1:-}"

    # Auto-detect system timezone if no default provided
    if [[ -z "$default" && -f /etc/localtime ]]; then
        default=$(readlink -f /etc/localtime 2>/dev/null \
            | sed 's|.*/zoneinfo/||') || true
    fi
    [[ -z "$default" ]] && default="UTC"

    # Build options: curated list + Other
    local choice
    # shellcheck disable=SC2086  # Intentional word splitting for menu options
    choice=$(ui_choose --header "Timezone" $TIMEZONES "Other")

    if [[ "$choice" == "Other" ]]; then
        local result
        result=$(ui_input "Timezone (e.g. America/New_York)" "$default")
        echo "${result:-$default}"
    else
        echo "$choice"
    fi
}

prompt_and_store_credentials() {
    local provider="$1"
    local vpn_type="$2"
    local key="${provider}:${vpn_type}"
    local cred="${PROVIDER_CREDS[$key]:-}"
    local help_url="${PROVIDER_HELP[$key]:-}"

    echo ""
    info "Credentials for $provider ($vpn_type)"
    if [[ -n "$help_url" ]]; then
        echo -e "  Get them at: ${C_CYAN}$help_url${C_NC}"
    fi
    echo ""

    case "$cred" in
        openvpn_user_pass)
            local user pass
            user=$(ui_input "OpenVPN Username")
            [[ -z "$user" ]] && error "Username cannot be empty" "exit"
            pass=$(ui_password "OpenVPN Password")
            [[ -z "$pass" ]] && error "Password cannot be empty" "exit"
            secret_set "torrent-openvpn-user" "$user"
            secret_set "torrent-openvpn-password" "$pass"
            ;;
        openvpn_user_only)
            local user
            user=$(ui_input "Account ID")
            [[ -z "$user" ]] && error "Account ID cannot be empty" "exit"
            secret_set "torrent-openvpn-user" "$user"
            ;;
        wireguard_key)
            local key_val
            key_val=$(ui_password "WireGuard Private Key")
            [[ -z "$key_val" ]] && error "Private key cannot be empty" "exit"
            secret_set "torrent-wireguard-key" "$key_val"
            ;;
        wireguard_key_addr)
            local key_val addr
            key_val=$(ui_password "WireGuard Private Key")
            [[ -z "$key_val" ]] && error "Private key cannot be empty" "exit"
            addr=$(ui_input "WireGuard Address (e.g. 10.64.222.21/32)")
            [[ -z "$addr" ]] && error "Address cannot be empty" "exit"
            secret_set "torrent-wireguard-key" "$key_val"
            # Address stored in config, not as secret (not sensitive)
            WG_ADDR_RESULT="$addr"
            ;;
        *)
            error "Unknown credential pattern for $key" "exit"
            ;;
    esac

    success "Credentials stored as Podman secrets"
}

# =============================================================================
# COMMANDS
# =============================================================================

# ===================
# install
# ===================
cmd_install() {
    ui_header "Gluetun + qBittorrent Container Setup"

    # Check if containers already exist
    if container_exists "gluetun" || container_exists "qbittorrent"; then
        warn "Containers already exist."
        if ui_confirm "Remove existing containers and reconfigure?"; then
            remove_containers
        else
            info "Use 'torrent-container edit' to modify config."
            return 0
        fi
    fi

    # Load paths config (DOWNLOAD_DIR, EXPORT_DIR from paths.conf)
    load_config
    TORRENT_DIR="$DOWNLOAD_DIR/torrents"
    info "Using paths:"
    echo "  Torrent dir: $TORRENT_DIR"
    echo "  Export dir:  $EXPORT_DIR"
    echo ""

    # Create data directories
    mkdir -p "$TORRENT_DIR"
    mkdir -p "$CONTAINER_DATA_DIR/qbittorrent"
    mkdir -p "$CONTAINER_DATA_DIR/gluetun"

    # --- Interactive configuration ---
    local provider vpn_type countries free_only tz puid pgid
    provider=$(prompt_provider)
    vpn_type=$(prompt_vpn_type "$provider")

    # Store credentials as Podman secrets
    WG_ADDR_RESULT=""
    prompt_and_store_credentials "$provider" "$vpn_type"

    countries=$(prompt_countries)
    free_only=$(prompt_free_only "$provider")
    tz=$(detect_timezone "")
    puid=$(id -u)
    pgid=$(id -g)

    # Generate API key for Gluetun control server auth
    local api_key
    api_key=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)

    # Save config
    save_container_config "$provider" "$vpn_type" "$countries" \
        "$free_only" "$tz" "$puid" "$pgid" "$WG_ADDR_RESULT" "$api_key"
    success "Configuration saved: $CONTAINER_CONF"

    # Create containers
    echo ""
    create_containers

    # Show qBittorrent logs for initial password
    echo ""
    podman logs qbittorrent 2>&1 | tail -20

    ui_banner "qBittorrent is running!" \
        "Web UI: http://localhost:18002" \
        "" \
        "IMPORTANT: Change the default password NOW!" \
        "  1. Open http://localhost:18002" \
        "  2. Login with temporary credentials shown in logs above" \
        "  3. Go to Settings > Web UI > Change password"

    ui_confirm "Press Enter once you have changed the password..." || true

    # Stop containers for setup completion
    echo ""
    info "Stopping containers for first-time setup completion..."
    podman stop qbittorrent gluetun 2>/dev/null || true

    # Final banner
    load_config
    TORRENT_DIR="$DOWNLOAD_DIR/torrents"
    ui_banner "Setup complete!" \
        "Detected directories:" \
        "  Torrent downloads: $TORRENT_DIR" \
        "  Export destination: $EXPORT_DIR" \
        "" \
        "Usage:" \
        "  torrent start    # Start VPN + qBittorrent" \
        "  torrent status   # Check status" \
        "  torrent stop     # Stop everything" \
        "" \
        "  torrent list     # List downloaded files" \
        "  torrent move 1   # Move file to $EXPORT_DIR" \
        "  torrent export   # Move all clean files" \
        "" \
        "  sudo quarantine  # Manage quarantined files" \
        "  torrent --help   # More options"
}

# ===================
# info
# ===================
cmd_info() {
    if ! load_container_config; then
        error "No configuration found. Run 'torrent-container install' first." "exit"
    fi

    ui_header "Torrent Container Configuration"

    echo -e "  ${C_BOLD}Provider:${C_NC}     $PROVIDER"
    echo -e "  ${C_BOLD}VPN Type:${C_NC}     $VPN_TYPE"
    echo -e "  ${C_BOLD}Countries:${C_NC}    $COUNTRIES"
    echo -e "  ${C_BOLD}Free Only:${C_NC}    $FREE_ONLY"
    echo -e "  ${C_BOLD}Timezone:${C_NC}     $TZ"
    echo -e "  ${C_BOLD}PUID/PGID:${C_NC}   $PUID/$PGID"
    if [[ -n "${WIREGUARD_ADDRESSES:-}" ]]; then
        echo -e "  ${C_BOLD}WG Address:${C_NC}   $WIREGUARD_ADDRESSES"
    fi
    echo ""

    # Secrets status
    echo -e "  ${C_BOLD}Credentials:${C_NC}"
    local needed
    needed=$(secrets_needed "$PROVIDER" "$VPN_TYPE")
    for secret_name in $needed; do
        if secret_exists "$secret_name"; then
            echo -e "    ${C_GREEN}*${C_NC} $secret_name"
        else
            echo -e "    ${C_RED}!${C_NC} $secret_name ${C_RED}(missing)${C_NC}"
        fi
    done
    echo ""

    # Container status
    echo -e "  ${C_BOLD}Containers:${C_NC}"
    for ct in gluetun qbittorrent; do
        if container_running "$ct"; then
            echo -e "    ${C_GREEN}* Running${C_NC}      $ct"
        elif container_exists "$ct"; then
            echo -e "    ${C_YELLOW}o Stopped${C_NC}      $ct"
        else
            echo -e "    ${C_RED}! Not created${C_NC}  $ct"
        fi
    done
    echo ""
}

# ===================
# edit
# ===================
cmd_edit() {
    if ! load_container_config; then
        error "No configuration found. Run 'torrent-container install' first." "exit"
    fi

    ui_header "Edit Container Configuration"

    # Save original values for comparison
    local orig_provider="$PROVIDER"
    local orig_vpn_type="$VPN_TYPE"

    # --- Provider ---
    local new_provider
    # shellcheck disable=SC2086
    new_provider=$(ui_choose --header "VPN Provider (current: $PROVIDER)" \
        $PROVIDERS "keep current")
    [[ "$new_provider" == "keep current" ]] && new_provider="$PROVIDER"

    # --- VPN Type ---
    local new_vpn_type
    local types=()
    [[ -n "${PROVIDER_CREDS["$new_provider:openvpn"]:-}" ]] && types+=("openvpn")
    [[ -n "${PROVIDER_CREDS["$new_provider:wireguard"]:-}" ]] && types+=("wireguard")
    types+=("keep current")
    new_vpn_type=$(ui_choose --header "VPN Type (current: $VPN_TYPE)" "${types[@]}")
    [[ "$new_vpn_type" == "keep current" ]] && new_vpn_type="$VPN_TYPE"

    # Validate the combination exists
    local new_key="${new_provider}:${new_vpn_type}"
    if [[ -z "${PROVIDER_CREDS[$new_key]:-}" ]]; then
        error "$new_provider does not support $new_vpn_type" "exit"
    fi

    # --- Countries ---
    local new_countries
    new_countries=$(prompt_countries "$COUNTRIES")

    # --- Free Only ---
    local new_free_only="$FREE_ONLY"
    if [[ "$FREE_ONLY_PROVIDERS" == *"$new_provider"* ]]; then
        new_free_only=$(ui_choose --header "Free Only (current: $FREE_ONLY)" \
            "off" "on" "keep current")
        [[ "$new_free_only" == "keep current" ]] && new_free_only="$FREE_ONLY"
    else
        new_free_only="off"
    fi

    # --- Handle credential changes ---
    local old_key="${orig_provider}:${orig_vpn_type}"
    local old_cred="${PROVIDER_CREDS[$old_key]:-}"
    local new_cred="${PROVIDER_CREDS[$new_key]:-}"
    WG_ADDR_RESULT="${WIREGUARD_ADDRESSES:-}"

    if [[ "$old_cred" != "$new_cred" ]]; then
        # Credential type changed — must re-enter credentials
        warn "Credential type changed ($old_cred -> $new_cred)."
        warn "Old secrets will be removed."
        echo ""
        local old_needed
        old_needed=$(secrets_needed "$orig_provider" "$orig_vpn_type")
        for secret_name in $old_needed; do
            secret_remove "$secret_name"
        done
        prompt_and_store_credentials "$new_provider" "$new_vpn_type"
    else
        # Same credential type — offer to update credentials
        if ui_confirm "Update credentials?"; then
            prompt_and_store_credentials "$new_provider" "$new_vpn_type"
        fi
    fi

    # Save updated config
    save_container_config "$new_provider" "$new_vpn_type" "$new_countries" \
        "$new_free_only" "$TZ" "$PUID" "$PGID" "$WG_ADDR_RESULT" "${GLUETUN_API_KEY:-}"
    success "Configuration saved"

    # Recreate containers
    echo ""
    if ui_confirm "Recreate containers with new config?"; then
        remove_containers
        create_containers
        podman stop qbittorrent gluetun 2>/dev/null || true
        echo ""
        success "Containers recreated."
        echo -e "  Run ${C_CYAN}torrent start${C_NC} to start the stack."
    else
        info "Config saved. Containers will use new config on next recreation."
    fi
}

# ===================
# update
# ===================
cmd_update() {
    if ! load_container_config; then
        error "No configuration found. Run 'torrent-container install' first." "exit"
    fi

    echo ""
    info "Pulling latest images..."

    local old_gluetun new_gluetun old_qbt new_qbt
    old_gluetun=$(podman image inspect --format '{{.Id}}' \
        "$IMAGE_GLUETUN" 2>/dev/null || echo "none")
    old_qbt=$(podman image inspect --format '{{.Id}}' \
        "$IMAGE_QBITTORRENT" 2>/dev/null || echo "none")

    podman pull "$IMAGE_GLUETUN"
    podman pull "$IMAGE_QBITTORRENT"

    new_gluetun=$(podman image inspect --format '{{.Id}}' \
        "$IMAGE_GLUETUN" 2>/dev/null || echo "none")
    new_qbt=$(podman image inspect --format '{{.Id}}' \
        "$IMAGE_QBITTORRENT" 2>/dev/null || echo "none")

    local gluetun_updated=false qbt_updated=false
    [[ "$old_gluetun" != "$new_gluetun" ]] && gluetun_updated=true
    [[ "$old_qbt" != "$new_qbt" ]] && qbt_updated=true

    if [[ "$gluetun_updated" == false && "$qbt_updated" == false ]]; then
        success "All images are up to date."
        return 0
    fi

    [[ "$gluetun_updated" == true ]] && success "Gluetun: new image pulled"
    [[ "$qbt_updated" == true ]] && success "qBittorrent: new image pulled"

    echo ""
    warn "Containers must be recreated to use the new images."
    ui_confirm "Recreate containers now?" || {
        info "Skipped. Run 'torrent-container update' again when ready."
        return 0
    }

    # Stop & remove
    remove_containers

    # Recreate from config
    create_containers

    # Stop — user starts with torrent start
    podman stop qbittorrent gluetun 2>/dev/null || true

    echo ""
    success "Containers recreated with new images."
    echo -e "  Run ${C_CYAN}torrent start${C_NC} to start the stack."
}

# ===================
# delete
# ===================
cmd_delete() {
    ui_header "Delete Torrent Containers"

    warn "This will remove:"
    echo "  - gluetun and qbittorrent containers"
    echo "  - Podman secrets (VPN credentials)"
    echo "  - Container configuration file"
    echo ""
    echo -e "  ${C_DIM}qBittorrent config and downloads are NOT removed${C_NC}"
    echo ""

    ui_confirm "Are you sure?" || { info "Cancelled."; return 0; }

    # Stop and remove containers
    remove_containers

    # Remove all torrent secrets
    secrets_remove_all

    # Remove config file
    rm -f "$CONTAINER_CONF"

    echo ""
    success "All container resources deleted"
}

# ===================
# help
# ===================
show_help() {
    echo ""
    echo -e "${C_BOLD}${C_CYAN}torrent-container${C_NC} - Container setup, config, and lifecycle"
    echo ""
    echo -e "${C_BOLD}USAGE:${C_NC}"
    echo -e "    ${C_CYAN}torrent-container${C_NC} ${C_YELLOW}<command>${C_NC}"
    echo ""
    echo -e "${C_BOLD}COMMANDS:${C_NC}"
    echo -e "    ${C_GREEN}install${C_NC}         Interactive setup (provider, credentials, countries)"
    echo -e "    ${C_GREEN}info${C_NC}            Show current configuration and container status"
    echo -e "    ${C_GREEN}edit${C_NC}            Modify config interactively, recreate containers"
    echo -e "    ${C_GREEN}update${C_NC}          Pull latest images and recreate if updated"
    echo -e "    ${C_GREEN}delete${C_NC}          Remove containers, secrets, and config"
    echo -e "    ${C_GREEN}help${C_NC}, --help    Show this help message"
    echo ""
    echo -e "${C_BOLD}SUPPORTED PROVIDERS:${C_NC}"
    echo -e "    ProtonVPN, Mullvad, NordVPN, Surfshark"
    echo ""
    echo -e "${C_BOLD}VPN PROTOCOLS:${C_NC}"
    echo -e "    OpenVPN, WireGuard"
    echo ""
    echo -e "${C_BOLD}CONFIG FILE:${C_NC}"
    echo -e "    ${C_YELLOW}$CONTAINER_CONF${C_NC}"
    echo ""
    echo -e "${C_BOLD}CREDENTIALS:${C_NC}"
    echo -e "    Stored as Podman secrets (not plaintext files)"
    echo -e "    List: ${C_CYAN}podman secret ls${C_NC}"
    echo ""
}

# =============================================================================
# CLI DISPATCH
# =============================================================================

# --- Interactive mode ---
if [[ -z "$ACTION" ]]; then
    ACTION=$(ui_choose \
        --header "Torrent Container - choose an action" \
        "install" "info" "edit" "update" "delete" "help")
fi

# --- Main ---
case "$ACTION" in
    install)          cmd_install ;;
    info|status)      cmd_info ;;
    edit)             cmd_edit ;;
    update)           cmd_update ;;
    delete)           cmd_delete ;;
    help|--help|-h)   show_help ;;
    *)
        error "Unknown command: $ACTION"
        echo "Run 'torrent-container --help' for usage"
        exit 1
        ;;
esac
