#!/bin/bash
# =============================================================================
# PATHS.SH - Locale-aware download path detection
# =============================================================================
# Detects download directories using XDG and generates paths.conf.
# Works on both French (Téléchargements) and English (Downloads) systems.
#
# Usage:
#   source "$LIB_DIR/paths.sh"
#
# Functions:
#   detect_download_dir [user]                  - Detect XDG download directory
#   detect_watch_dirs [user]                    - Build array of dirs to monitor
#   generate_paths_conf [user] [output_file]    - Generate paths.conf
#
# Version: 0.1.0
# =============================================================================

[[ -n "${_LIB_PATHS_LOADED:-}" ]] && return 0
readonly _LIB_PATHS_LOADED=1

source "$(dirname "${BASH_SOURCE[0]}")/core.sh"

# Detect download directory for a user using XDG
detect_download_dir() {
    local user="${1:-$USER}"
    local home_dir

    # Get user's home directory
    if [[ "$user" == "$USER" ]]; then
        home_dir="$HOME"
    else
        home_dir=$(getent passwd "$user" | cut -d: -f6)
        [[ -z "$home_dir" ]] && home_dir="/home/$user"
    fi

    local download_dir=""

    # Method 1: Use xdg-user-dir if available and running as the user
    if [[ "$user" == "$USER" ]] && command -v xdg-user-dir &>/dev/null; then
        download_dir=$(xdg-user-dir DOWNLOAD 2>/dev/null)
    fi

    # Method 2: Read from user-dirs.dirs config file
    if [[ -z "$download_dir" || "$download_dir" == "$home_dir" ]]; then
        local user_dirs_file="$home_dir/.config/user-dirs.dirs"
        if [[ -f "$user_dirs_file" ]]; then
            # Parse XDG_DOWNLOAD_DIR from the file
            # Format: XDG_DOWNLOAD_DIR="$HOME/Téléchargements"
            download_dir=$(grep -E '^XDG_DOWNLOAD_DIR=' "$user_dirs_file" 2>/dev/null | cut -d'"' -f2)
            # Expand $HOME in the path
            download_dir="${download_dir//\$HOME/$home_dir}"
        fi
    fi

    # Method 3: Check for common directory names
    if [[ -z "$download_dir" || ! -d "$download_dir" ]]; then
        # Check French first (more specific), then English
        if [[ -d "$home_dir/Téléchargements" ]]; then
            download_dir="$home_dir/Téléchargements"
        elif [[ -d "$home_dir/Downloads" ]]; then
            download_dir="$home_dir/Downloads"
        else
            # Default based on locale
            local lang="${LANG:-en_US.UTF-8}"
            if [[ "$lang" == fr_* ]]; then
                download_dir="$home_dir/Téléchargements"
            else
                download_dir="$home_dir/Downloads"
            fi
        fi
    fi

    echo "$download_dir"
}

# Build array of directories to watch for downloads
detect_watch_dirs() {
    local user="${1:-$USER}"
    local home_dir

    if [[ "$user" == "$USER" ]]; then
        home_dir="$HOME"
    else
        home_dir=$(getent passwd "$user" | cut -d: -f6)
        [[ -z "$home_dir" ]] && home_dir="/home/$user"
    fi

    local download_dir
    download_dir=$(detect_download_dir "$user")

    # Build unique list of directories
    local -a dirs=()

    # Always include main download dir
    dirs+=("$download_dir")

    # Check for other common download locations that might exist
    for extra_dir in "$home_dir/Downloads" "$home_dir/Téléchargements"; do
        if [[ -d "$extra_dir" && "$extra_dir" != "$download_dir" ]]; then
            dirs+=("$extra_dir")
        fi
    done

    # Output as newline-separated for easy parsing
    printf '%s\n' "${dirs[@]}" | sort -u
}

# Generate paths.conf configuration file
generate_paths_conf() {
    local user="${1:-$USER}"

    local home_dir
    if [[ "$user" == "$USER" ]]; then
        home_dir="$HOME"
    else
        home_dir=$(getent passwd "$user" | cut -d: -f6)
        [[ -z "$home_dir" ]] && home_dir="/home/$user"
    fi

    local download_dir
    download_dir=$(detect_download_dir "$user")

    # Get watch dirs as array
    local watch_dirs_str=""
    while IFS= read -r dir; do
        [[ -n "$dir" ]] && watch_dirs_str+="    \"$dir\"\n"
    done < <(detect_watch_dirs "$user")

    cat << EOF
# =============================================================================
# Downloads Manager - Path Configuration
# =============================================================================
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# User: $user
# Locale: ${LANG:-unknown}
#
# This file is auto-generated by lib/paths.sh
# You can edit it manually to override detected paths
# =============================================================================

# Target user for downloads
TARGET_USER="$user"
TARGET_HOME="$home_dir"

# Main download directory (locale-aware)
DOWNLOAD_DIR="$download_dir"

# Export destination (where files are moved after processing)
EXPORT_DIR="$download_dir"

# Directories to monitor for automatic scanning
WATCH_DIRS=(
$(echo -e "$watch_dirs_str"))
EOF
}
